### ISSUE TITLE
GenerateFormAsync silently failing

### ISSUE THREAD

**Issue by Rockerby** [vendrhub/vendr-payment-provider-opayo#5]
Hey,

We're at the starting block with this plugin and we're trying to integrate alongside the [Vendr Checkout](https://github.com/vendrhub/vendr-checkout/) and when we're trying to access the /checkout/review-order/ page we're getting a constantly loading page.

I've narrowed this down to [OpayoServerPaymentProvider.cs](https://github.com/vendrhub/vendr-payment-provider-opayo/blob/e0bd1e39e5565dc8879d3c1d26c3ed944b885fc5/src/Vendr.PaymentProviders.Opayo/OpayoServerPaymentProvider.cs#L63) and it looks like the await call is failing and causing a deadlock.

Turns out that the underlying issue is the fact my notification URL was invalid, but the package didn't tell me that or put anything out in the logs.

For reference:
Umbraco 8.18.2
Vendr.Core 2.0.0
Vendr.Checkout 2.1.0

**Comment by Rockerby** [comment]
Thought a little video of the issue may help - https://vimeo.com/729513315/e42a75b73c

**Comment by Rockerby** [comment]
@mattbrailsford just checking in on this issue?

**Comment by mattbrailsford** [comment]
Hey @Rockerby 

Sorry, not sure how, but I completely missed this 🤔

Hmm, I could implement your fix, but I'm a bit confused as to why the async call just fails to return. Shouldn't that at least still error?

**Comment by mattbrailsford** [comment]
It might be interesting to debug further into the client entity as that code is all present in the provider code (in the API namespace) to see if you can locate the actual location something goes wrong / stalls. I think it would be much  better if we can make the async stuff work correctly than just forcing it to run sync.

**Comment by mattbrailsford** [comment]
Hmm, I wonder if this is throwing something other than a `FlurlHttpException` and so it's just getting ignored? https://github.com/vendrhub/vendr-payment-provider-opayo/blob/v2/dev/src/Vendr.PaymentProviders.Opayo/Api/OpayoClient.cs#L121

You can see here that this method is used to fetch the relevant data https://github.com/vendrhub/vendr-payment-provider-opayo/blob/v2/dev/src/Vendr.PaymentProviders.Opayo/Api/OpayoClient.cs#L30

**Comment by Rockerby** [comment]
Cheers @mattbrailsford. I've spent some time looking into this and it's not the generic Exception being thrown - it's definitely a deadlock issue.

Taking inspiration from [people who know way more](https://stackoverflow.com/a/10351400/1848057) about this than I do, it looks like this is down to hi-jinks with the `SynchronizationContext` and making use of the HttpClient (in Flurl) which overrides the main request coming in.

I've refactored the code change I made to use `continueOnCapturedContext` `false` throughout the API calls to stop calls being queued up on the main `SynchronizationContext`, which continues to run everything async, but prevents the deadlock.

**Comment by mattbrailsford** [comment]
Awesome work @Rockerby Sounds like I make have to go do that with the other payment providers that use Flurl 🤦‍♂️

Good to know though. I'll get that PR merged in.

Thanks for invetigating this further and finding the better solution.

**Comment by mattbrailsford** [comment]
If you want to test our build, we've got a 2.0.1-beta009 on our unstable NuGet feed at https://nuget.outfield.digital/unstable/vendr/v3/index.json

**Comment by Rockerby** [comment]
Cheers pal! I'll give that a blast and let you know 👍

**Comment by Rockerby** [comment]
Just to update to say I've tested this using the beta package and it's working as expected. Thanks @mattbrailsford

**Comment by mattbrailsford** [comment]
Thanks @Rockerby There should be a published 2.0.1 release now.

Thanks again for submitting this and doing the digging 👍
